# Generated by Django 4.2.13 on 2024-06-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="Category",
        ),
        migrations.AlterField(
            model_name="item",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="item.category",
            ),
            preserve_default=False,
        ),
    ]
